backend:
  name: auth0
  client_id: jJKgSgYnVE1KUM8n7P1bTQhS4KsUKgBr
  domain: dev-cau83froo7jdms2y.us.auth0.com


media_folder: "bilder"
public_folder: "/bilder"

collections:
  - name: "angebote"
    label: "Angebote"
    folder: ""
    files:
      - file: "angebote.json"
        label: "Angebotsliste"
        name: "angebotsliste"
        fields:
          - label: "Angebote"
            name: "entries"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Titel", name: "titel", widget: "string" }
              - { label: "Bild", name: "bild", widget: "image" }
              - { label: "Details", name: "details", widget: "text" }
              - { label: "Preis", name: "preis", widget: "string" }
              - { label: "Link", name: "mehr", widget: "string", required: false }
